### PR TITLE
Add editorial for January 13 2022

### PR DESCRIPTION
**Pull request by inoxx03**

### CODE REVIEW

**Comment by rpelisse** [comment]
@inoxx03 ignore the result of the CI build, it sadly always fails during the SFTP part. As it did not failed before, you're are good to go.

**Comment by inoxx03** [comment]
@rpelisse Thank you for the heads up. The editorial is ready.
@fmarchioni @oraNod if you have a chance to take a look, please let me know if you have comments or suggestions for content to add.
Thank you.

**Comment by rpelisse** [comment]
@inoxx03 I'll merge it tomorrow because it will get release almost immediately and it's supposed to come out on Thursday.

**Comment by inoxx03** [comment]
@rpelisse That is absolutely OK. Thank you!
I've added my profile photo, too

**Comment by fmarchioni** [comment]
> @rpelisse Thank you for the heads up. The editorial is ready. @fmarchioni @oraNod if you have a chance to take a look, please let me know if you have comments or suggestions for content to add. Thank you.

Looks good to me, just a thing: I see Quarkus release 2.6.0 is announced in the editorial- I see the current stable release is 2.6.1: https://quarkus.io/

**Pull request merged**
